/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as MinhasObrasRouteImport } from './routes/minhas-obras'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrasIdRouteImport } from './routes/obras.$id'
import { Route as GestaoUtilizadoresRouteImport } from './routes/gestao_.utilizadores'
import { Route as GestaoRubricasRouteImport } from './routes/gestao_.rubricas'
import { Route as ClientesIdRouteImport } from './routes/clientes_.$id'
import { Route as ObrasIdLancamentosRouteImport } from './routes/obras_.$id.lancamentos'
import { Route as GestaoObrasIdRouteImport } from './routes/gestao_.obras.$id'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasObrasRoute = MinhasObrasRouteImport.update({
  id: '/minhas-obras',
  path: '/minhas-obras',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdRoute = ObrasIdRouteImport.update({
  id: '/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoUtilizadoresRoute = GestaoUtilizadoresRouteImport.update({
  id: '/gestao_/utilizadores',
  path: '/gestao/utilizadores',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRubricasRoute = GestaoRubricasRouteImport.update({
  id: '/gestao_/rubricas',
  path: '/gestao/rubricas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes_/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdLancamentosRoute = ObrasIdLancamentosRouteImport.update({
  id: '/obras_/$id/lancamentos',
  path: '/obras/$id/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoObrasIdRoute = GestaoObrasIdRouteImport.update({
  id: '/gestao_/obras/$id',
  path: '/gestao/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/minhas-obras': typeof MinhasObrasRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/gestao/rubricas': typeof GestaoRubricasRoute
  '/gestao/utilizadores': typeof GestaoUtilizadoresRoute
  '/obras/$id': typeof ObrasIdRoute
  '/gestao/obras/$id': typeof GestaoObrasIdRoute
  '/obras/$id/lancamentos': typeof ObrasIdLancamentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/minhas-obras': typeof MinhasObrasRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/gestao/rubricas': typeof GestaoRubricasRoute
  '/gestao/utilizadores': typeof GestaoUtilizadoresRoute
  '/obras/$id': typeof ObrasIdRoute
  '/gestao/obras/$id': typeof GestaoObrasIdRoute
  '/obras/$id/lancamentos': typeof ObrasIdLancamentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/minhas-obras': typeof MinhasObrasRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes_/$id': typeof ClientesIdRoute
  '/gestao_/rubricas': typeof GestaoRubricasRoute
  '/gestao_/utilizadores': typeof GestaoUtilizadoresRoute
  '/obras/$id': typeof ObrasIdRoute
  '/gestao_/obras/$id': typeof GestaoObrasIdRoute
  '/obras_/$id/lancamentos': typeof ObrasIdLancamentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/gestao'
    | '/login'
    | '/minhas-obras'
    | '/relatorios'
    | '/clientes/$id'
    | '/gestao/rubricas'
    | '/gestao/utilizadores'
    | '/obras/$id'
    | '/gestao/obras/$id'
    | '/obras/$id/lancamentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/gestao'
    | '/login'
    | '/minhas-obras'
    | '/relatorios'
    | '/clientes/$id'
    | '/gestao/rubricas'
    | '/gestao/utilizadores'
    | '/obras/$id'
    | '/gestao/obras/$id'
    | '/obras/$id/lancamentos'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/gestao'
    | '/login'
    | '/minhas-obras'
    | '/relatorios'
    | '/clientes_/$id'
    | '/gestao_/rubricas'
    | '/gestao_/utilizadores'
    | '/obras/$id'
    | '/gestao_/obras/$id'
    | '/obras_/$id/lancamentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  GestaoRoute: typeof GestaoRoute
  LoginRoute: typeof LoginRoute
  MinhasObrasRoute: typeof MinhasObrasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ClientesIdRoute: typeof ClientesIdRoute
  GestaoRubricasRoute: typeof GestaoRubricasRoute
  GestaoUtilizadoresRoute: typeof GestaoUtilizadoresRoute
  ObrasIdRoute: typeof ObrasIdRoute
  GestaoObrasIdRoute: typeof GestaoObrasIdRoute
  ObrasIdLancamentosRoute: typeof ObrasIdLancamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-obras': {
      id: '/minhas-obras'
      path: '/minhas-obras'
      fullPath: '/minhas-obras'
      preLoaderRoute: typeof MinhasObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id': {
      id: '/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof ObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/utilizadores': {
      id: '/gestao_/utilizadores'
      path: '/gestao/utilizadores'
      fullPath: '/gestao/utilizadores'
      preLoaderRoute: typeof GestaoUtilizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/rubricas': {
      id: '/gestao_/rubricas'
      path: '/gestao/rubricas'
      fullPath: '/gestao/rubricas'
      preLoaderRoute: typeof GestaoRubricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes_/$id': {
      id: '/clientes_/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras_/$id/lancamentos': {
      id: '/obras_/$id/lancamentos'
      path: '/obras/$id/lancamentos'
      fullPath: '/obras/$id/lancamentos'
      preLoaderRoute: typeof ObrasIdLancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/obras/$id': {
      id: '/gestao_/obras/$id'
      path: '/gestao/obras/$id'
      fullPath: '/gestao/obras/$id'
      preLoaderRoute: typeof GestaoObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  GestaoRoute: GestaoRoute,
  LoginRoute: LoginRoute,
  MinhasObrasRoute: MinhasObrasRoute,
  RelatoriosRoute: RelatoriosRoute,
  ClientesIdRoute: ClientesIdRoute,
  GestaoRubricasRoute: GestaoRubricasRoute,
  GestaoUtilizadoresRoute: GestaoUtilizadoresRoute,
  ObrasIdRoute: ObrasIdRoute,
  GestaoObrasIdRoute: GestaoObrasIdRoute,
  ObrasIdLancamentosRoute: ObrasIdLancamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
