/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as EncarregadoRouteImport } from './routes/encarregado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrasIdRouteImport } from './routes/obras.$id'
import { Route as GestaoUtilizadoresRouteImport } from './routes/gestao.utilizadores'
import { Route as GestaoRubricasRouteImport } from './routes/gestao.rubricas'
import { Route as GestaoObrasIdRouteImport } from './routes/gestao_.obras.$id'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const EncarregadoRoute = EncarregadoRouteImport.update({
  id: '/encarregado',
  path: '/encarregado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdRoute = ObrasIdRouteImport.update({
  id: '/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoUtilizadoresRoute = GestaoUtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoRubricasRoute = GestaoRubricasRouteImport.update({
  id: '/rubricas',
  path: '/rubricas',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoObrasIdRoute = GestaoObrasIdRouteImport.update({
  id: '/gestao_/obras/$id',
  path: '/gestao/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/encarregado': typeof EncarregadoRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/gestao/rubricas': typeof GestaoRubricasRoute
  '/gestao/utilizadores': typeof GestaoUtilizadoresRoute
  '/obras/$id': typeof ObrasIdRoute
  '/gestao/obras/$id': typeof GestaoObrasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/encarregado': typeof EncarregadoRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/gestao/rubricas': typeof GestaoRubricasRoute
  '/gestao/utilizadores': typeof GestaoUtilizadoresRoute
  '/obras/$id': typeof ObrasIdRoute
  '/gestao/obras/$id': typeof GestaoObrasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/encarregado': typeof EncarregadoRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/gestao/rubricas': typeof GestaoRubricasRoute
  '/gestao/utilizadores': typeof GestaoUtilizadoresRoute
  '/obras/$id': typeof ObrasIdRoute
  '/gestao_/obras/$id': typeof GestaoObrasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/encarregado'
    | '/gestao'
    | '/login'
    | '/relatorios'
    | '/gestao/rubricas'
    | '/gestao/utilizadores'
    | '/obras/$id'
    | '/gestao/obras/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/encarregado'
    | '/gestao'
    | '/login'
    | '/relatorios'
    | '/gestao/rubricas'
    | '/gestao/utilizadores'
    | '/obras/$id'
    | '/gestao/obras/$id'
  id:
    | '__root__'
    | '/'
    | '/encarregado'
    | '/gestao'
    | '/login'
    | '/relatorios'
    | '/gestao/rubricas'
    | '/gestao/utilizadores'
    | '/obras/$id'
    | '/gestao_/obras/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EncarregadoRoute: typeof EncarregadoRoute
  GestaoRoute: typeof GestaoRouteWithChildren
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ObrasIdRoute: typeof ObrasIdRoute
  GestaoObrasIdRoute: typeof GestaoObrasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encarregado': {
      id: '/encarregado'
      path: '/encarregado'
      fullPath: '/encarregado'
      preLoaderRoute: typeof EncarregadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id': {
      id: '/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof ObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/utilizadores': {
      id: '/gestao/utilizadores'
      path: '/utilizadores'
      fullPath: '/gestao/utilizadores'
      preLoaderRoute: typeof GestaoUtilizadoresRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/rubricas': {
      id: '/gestao/rubricas'
      path: '/rubricas'
      fullPath: '/gestao/rubricas'
      preLoaderRoute: typeof GestaoRubricasRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao_/obras/$id': {
      id: '/gestao_/obras/$id'
      path: '/gestao/obras/$id'
      fullPath: '/gestao/obras/$id'
      preLoaderRoute: typeof GestaoObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GestaoRouteChildren {
  GestaoRubricasRoute: typeof GestaoRubricasRoute
  GestaoUtilizadoresRoute: typeof GestaoUtilizadoresRoute
}

const GestaoRouteChildren: GestaoRouteChildren = {
  GestaoRubricasRoute: GestaoRubricasRoute,
  GestaoUtilizadoresRoute: GestaoUtilizadoresRoute,
}

const GestaoRouteWithChildren =
  GestaoRoute._addFileChildren(GestaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EncarregadoRoute: EncarregadoRoute,
  GestaoRoute: GestaoRouteWithChildren,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  ObrasIdRoute: ObrasIdRoute,
  GestaoObrasIdRoute: GestaoObrasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
